import React from 'react';

const countryCodes = [
  { code: '+998', name: 'UZ' },
  { code: '+7', name: 'RU' },
  { code: '+992', name: 'TJ' },
  { code: '+90', name: 'TR' },
  { code: '+996', name: 'KG' },
  { code: '+993', name: 'TM' },
  { code: '+86', name: 'CN' },
  { code: '+93', name: 'AF' },
  { code: '+374', name: 'AM' },
  { code: '+994', name: 'AZ' },
  { code: '+375', name: 'BY' },
  { code: '+380', name: 'UA' },
  { code: '+995', name: 'GE' },
  { code: '+972', name: 'IL' },
  { code: '+98', name: 'IR' },
  { code: '+962', name: 'JO' },
  { code: '+964', name: 'IQ' },
  { code: '+965', name: 'KW' },
  { code: '+966', name: 'SA' },
  { code: '+968', name: 'OM' },
  { code: '+971', name: 'AE' },
  { code: '+974', name: 'QA' },
  { code: '+963', name: 'SY' },
  { code: '+961', name: 'LB' },
  { code: '+20', name: 'EG' },
  { code: '+92', name: 'PK' },
  { code: '+91', name: 'IN' },
  { code: '+880', name: 'BD' },
  { code: '+94', name: 'LK' },
  { code: '+960', name: 'MV' },
  { code: '+60', name: 'MY' },
  { code: '+65', name: 'SG' },
  { code: '+66', name: 'TH' },
  { code: '+63', name: 'PH' },
  { code: '+84', name: 'VN' },
  { code: '+62', name: 'ID' },
  { code: '+855', name: 'KH' },
  { code: '+852', name: 'HK' },
  { code: '+853', name: 'MO' },
  { code: '+81', name: 'JP' },
  { code: '+82', name: 'KR' },
  { code: '+976', name: 'MN' },
  { code: '+977', name: 'NP' },
  { code: '+967', name: 'YE' },
  { code: '+973', name: 'BH' },
  { code: '+970', name: 'PS' },
  { code: '+213', name: 'DZ' },
  { code: '+216', name: 'TN' },
  { code: '+218', name: 'LY' },
  { code: '+212', name: 'MA' },
  { code: '+249', name: 'SD' },
  { code: '+252', name: 'SO' },
  { code: '+251', name: 'ET' },
  { code: '+256', name: 'UG' },
  { code: '+254', name: 'KE' },
  { code: '+255', name: 'TZ' },
  { code: '+250', name: 'RW' },
  { code: '+257', name: 'BI' },
  { code: '+253', name: 'DJ' },
  { code: '+27', name: 'ZA' },
  { code: '+263', name: 'ZW' },
  { code: '+260', name: 'ZM' },
  { code: '+265', name: 'MW' },
  { code: '+264', name: 'NA' },
  { code: '+267', name: 'BW' },
  { code: '+268', name: 'SZ' },
  { code: '+266', name: 'LS' },
  { code: '+262', name: 'RE' },
  { code: '+269', name: 'KM' },
  { code: '+261', name: 'MG' },
  { code: '+222', name: 'MR' },
  { code: '+221', name: 'SN' },
  { code: '+223', name: 'ML' },
  { code: '+224', name: 'GN' },
  { code: '+225', name: 'CI' },
  { code: '+226', name: 'BF' },
  { code: '+227', name: 'NE' },
  { code: '+228', name: 'TG' },
  { code: '+229', name: 'BJ' },
  { code: '+230', name: 'MU' },
  { code: '+231', name: 'LR' },
  { code: '+232', name: 'SL' },
  { code: '+233', name: 'GH' },
  { code: '+234', name: 'NG' },
  { code: '+235', name: 'TD' },
  { code: '+236', name: 'CF' },
  { code: '+237', name: 'CM' },
  { code: '+238', name: 'CV' },
  { code: '+239', name: 'ST' },
  { code: '+240', name: 'GQ' },
  { code: '+241', name: 'GA' },
  { code: '+242', name: 'CG' },
  { code: '+243', name: 'CD' },
  { code: '+244', name: 'AO' },
  { code: '+245', name: 'GW' },
  { code: '+246', name: 'IO' },
  { code: '+248', name: 'SC' },
  { code: '+258', name: 'MZ' },
  { code: '+290', name: 'SH' },
  { code: '+291', name: 'ER' },
  { code: '+297', name: 'AW' },
  { code: '+298', name: 'FO' },
  { code: '+299', name: 'GL' },
  { code: '+350', name: 'GI' },
  { code: '+351', name: 'PT' },
  { code: '+352', name: 'LU' },
  { code: '+353', name: 'IE' },
  { code: '+354', name: 'IS' },
  { code: '+355', name: 'AL' },
  { code: '+356', name: 'MT' },
  { code: '+357', name: 'CY' },
  { code: '+358', name: 'FI' },
  { code: '+359', name: 'BG' },
  { code: '+370', name: 'LT' },
  { code: '+371', name: 'LV' },
  { code: '+372', name: 'EE' },
  { code: '+373', name: 'MD' },
  { code: '+376', name: 'AD' },
  { code: '+377', name: 'MC' },
  { code: '+378', name: 'SM' },
  { code: '+381', name: 'RS' },
  { code: '+382', name: 'ME' },
  { code: '+383', name: 'XK' },
  { code: '+385', name: 'HR' },
  { code: '+386', name: 'SI' },
  { code: '+387', name: 'BA' },
  { code: '+389', name: 'MK' },
  { code: '+420', name: 'CZ' },
  { code: '+421', name: 'SK' },
  { code: '+423', name: 'LI' },
  { code: '+501', name: 'BZ' },
  { code: '+502', name: 'GT' },
  { code: '+503', name: 'SV' },
  { code: '+504', name: 'HN' },
  { code: '+505', name: 'NI' },
  { code: '+506', name: 'CR' },
  { code: '+507', name: 'PA' },
  { code: '+508', name: 'PM' },
  { code: '+509', name: 'HT' },
  { code: '+590', name: 'GP' },
  { code: '+591', name: 'BO' },
  { code: '+592', name: 'GY' },
  { code: '+593', name: 'EC' },
  { code: '+594', name: 'GF' },
  { code: '+595', name: 'PY' },
  { code: '+596', name: 'MQ' },
  { code: '+597', name: 'SR' },
  { code: '+598', name: 'UY' },
  { code: '+599', name: 'CW' },
  { code: '+670', name: 'TL' },
  { code: '+672', name: 'NF' },
  { code: '+673', name: 'BN' },
  { code: '+674', name: 'NR' },
  { code: '+675', name: 'PG' },
  { code: '+676', name: 'TO' },
  { code: '+677', name: 'SB' },
  { code: '+678', name: 'VU' },
  { code: '+679', name: 'FJ' },
  { code: '+680', name: 'PW' },
  { code: '+681', name: 'WF' },
  { code: '+682', name: 'CK' },
  { code: '+683', name: 'NU' },
  { code: '+685', name: 'WS' },
  { code: '+686', name: 'KI' },
  { code: '+687', name: 'NC' },
  { code: '+688', name: 'TV' },
  { code: '+689', name: 'PF' },
  { code: '+690', name: 'TK' },
  { code: '+691', name: 'FM' },
  { code: '+692', name: 'MH' },
  { code: '+850', name: 'KP' },
  { code: '+856', name: 'LA' },
  { code: '+886', name: 'TW' },
  { code: '+969', name: 'YD' }
];

export function CountryCodeSelector({ selectedCode, onCodeChange, language }) {
  const handleChange = (e) => {
    onCodeChange(e.target.value);
  };

  return (
    <select
      value={selectedCode}
      onChange={handleChange}
      className="w-full py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-orange-500 transition-all appearance-none bg-white pl-4 pr-8"
    >
      {countryCodes.map((country) => (
        <option key={country.code} value={country.code}>
          {country.code} ({country.name})
        </option>
      ))}
    </select>
  );
}